#!/bin/bash
# insta485run
# Stop on errors
# See https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/

set -Eeuo pipefail

if [ ! -f var/imagician.sqlite3 ]; then
    ./bin/IMAGician_db create
fi
source env/bin/activate
export FLASK_ENV=development
export FLASK_APP=imagician
flask run --host 0.0.0.0 --port 8000

pkill -f gunicorn
gunicorn -b localhost:8000 -w 2 -D imagician:app